// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type NewLoan struct {
	Amount float64   `json:"amount"`
	Rate   float64   `json:"rate"`
	Start  time.Time `json:"start"`
}
